### ISSUE TITLE
Missing major version tags to support action use

### ISSUE THREAD

**Issue by stevenh** [bufbuild/buf-breaking-action#104]
It's idiomatic to create major version tags so users can use them in their actions reducing code churn to get the latest compatible version e.g.
`bufbuild/buf-breaking-action@v1`

Could you add the creation of:
* `v<major>`

You can see this in practice [actions/checkout](https://github.com/actions/checkout/tags).

**Comment by joshcarp** [comment]
It looks like this behaviour already is already supported _without_ explicitly tagging a `v<major>` git tag. We already reference this in our docs and I've verified that it works. 
With this being said, I can't find any github docs on this behaviour, so we'll look into explicitly adding a `v1` semver tag, which will also allow it to show up in the marketplace drop down

**Comment by stevenh** [comment]
Thanks @joshcarp
