### ISSUE TITLE
False positive breaking change widening field from int32 to int64?

### ISSUE THREAD

**Issue by marko-asplund** [bufbuild/buf-breaking-action#110]
I'm getting the following error when changing a field type from int32 to int64:
```
Error: Field "1" on message "FooBar" changed type from "int32" to "int64".
```

Proto 3 [docs](https://protobuf.dev/programming-guides/proto3/#updating) appear to imply that int32/64 types are compatible, so is the above error a false positive?

> int32, uint32, int64, uint64, and bool are all compatible – this means you can change a field from one of these types to another without breaking forwards- or backwards-compatibility. If a number is parsed from the wire which doesn’t fit in the corresponding type, you will get the same effect as if you had cast the number to that type in C++ (for example, if a 64-bit number is read as an int32, it will be truncated to 32 bits).

**Comment by srikrsna-buf** [comment]
Hey! They are compatible at the `WIRE` level, more often than not the generated code will break. If you just care about `WIRE` compatibility you can switch to that: https://buf.build/docs/breaking/overview#rules-and-categories

**Comment by marko-asplund** [comment]
Makes sense - thank you @srikrsna-buf ! 🙇

**Comment by marko-asplund** [comment]
I'm having trouble changing `int32` to `int64` with `WIRE` level compatiblity:

```
me@laptop ~ % buf breaking --against-config buf.yaml --against '.git#branch=master'

me@laptop ~ % buf breaking --against '.git#branch=master'
schema/foo.proto:14:5:Field "5" on message "Foo" changed type from "int32" to "int64".
```

Here's how the config looks like (in local repo, changes uncommitted)
```
...
breaking:
  use:
    - WIRE
...
```

This change should be allowed with `WIRE` level compatibility check, right? 🤔 
This is with buf version 1.26.1.

**Comment by srikrsna-buf** [comment]
This works for me: `buf breaking  --against .git#branch=main` with the following `buf.yaml`:

```yaml
version: v1
breaking:
  use:
    - WIRE
lint:
  use:
    - DEFAULT
```

**Comment by marko-asplund** [comment]
Our config file specified version `v1beta1`, and with that config file version `WIRE` level compatibility check fails for `int32` ==> `int64` type change, whereas with `v1` it succeeds.
