### ISSUE TITLE
buf-breaking-action v1.1.4 does not support v2 config

### ISSUE THREAD

**Issue by ymmt2005** [bufbuild/buf-breaking-action#138]
We have converted our `buf.yaml` to v2 format, and now get
the following error with the latest version, v1.1.4, of this action.

```
Run bufbuild/buf-breaking-action@c57b3d842a5c3f3b454756ef65305a50a587c5ba
Failure: buf.yaml has an invalid "version: v2" set. Please add "version: v1". See https://docs.buf.build/faq for more details
Error: Failure: api/buf.yaml has an invalid "version: v2" set. Please add "version: v1". See https://docs.buf.build/faq for more details
```

**Comment by pkwarren** [comment]
Which version of https://github.com/bufbuild/buf-setup-action are you using? This action depends on buf-setup-action to download the Buf CLI. If you are upgraded to `v1.32.0` or later of that action (or follow the `v1` tag), it should work with v2 configs.

**Comment by ymmt2005** [comment]
Ah, yes. I used v1.31.0. Thank you for your help!
