### ISSUE TITLE
Add --exclude-imports input

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf-breaking-action#14]
The `buf breaking` command supports the `--exclude-imports` flag, so we should expose this in the [action.yml](https://github.com/bufbuild/buf-breaking-action/blob/4280330ef4fe7f88fd94967c9ac496b3ac0d71c8/action.yml#L7).

**Comment by thara** [comment]
@amckinney We also needs `--exclude-path` option's support.

I found #20  but it has closed.
Are there something to obstacle to support such options?

**Comment by ka2n** [comment]
The `buf.yaml` configuration allows for the exclusion of specific proto files.
https://buf.build/docs/configuration/v1/buf-yaml#use-1

**Comment by emcfarlane** [comment]
These two parameters `exclude_imports` and `exclude_paths` have been added to the new [`buf-action`](https://github.com/bufbuild/buf-action). Closing in favor of using this action to support this config.
