### ISSUE TITLE
Ability to approve breaking change

### ISSUE THREAD

**Issue by longility** [bufbuild/buf-breaking-action#15]
I believe there are times where we may accept breaking changes to where the buf-breaking check should not block merging. A good example is if the contract is still being in development. Here is an example in graphQL: https://graphql-inspector.com/docs/products/action#approve-label

**Comment by longility** [comment]
Is this something that is desired and appropriate for this github action?

**Comment by johanbrandhorst** [comment]
Isn't this usually something you can override as and when necessary as an end user? Is it very common for actions to provide this? I expect we'll want to avoid adding this sort of feature without a clear indication of need in the community or well established standard among actions.

**Comment by longility** [comment]
> Isn't this usually something you can override as and when necessary as an end user?

Can you elaborate what that looks like? For us, I don't see how we can work around it if we want to make this check a required check and have explicit approval of breaking changes.

**Comment by johanbrandhorst** [comment]
In my experience, admins are usually allowed to override required checks, so perhaps having an admin merge your change will be explicit enough?

**Comment by longility** [comment]
That is dependent on the repo protection rules on the branch. For us, we decided that admin should not be able to workaround the process of merging PRs. That is a coupling on how this github action works. So basically, you would have in documentation...

> To approve breaking changes, the admin should be allowed to merge to PR regardless of failed checks. Make sure you have that setting in the protection rule.

That doesn't seem like a desirable DX for the GHA consumer.

**Comment by johanbrandhorst** [comment]
That's a fair point, we'll have to think about it! Do you know how other actions implement this?

**Comment by longility** [comment]
Link I shared earlier: https://graphql-inspector.com/docs/products/action#approve-label
This is the codebase: https://github.com/kamilkisiela/graphql-inspector

There may be others. I would think of schema check and see what is in the wild. If need help pulling more resources. I can try.

**Comment by amckinney** [comment]
We actually support an [ignore_unstable_packages](https://docs.buf.build/breaking/configuration#ignore_unstable_packages) option that allows breaking changes for pre-production APIs.

I know it's not quite the same feature you're describing, but hopefully that will help you out in the meantime. I'm not sure that we'll commit to making this as an interactive experience, but I can see the use case so we'll be sure to take a closer look!

If you're so inclined to take a look, we always welcome contributions!

**Comment by zacbir** [comment]
Having gone through this myself today, we've decided that we're okay with some level of churn landing on main between releases, but it seems trying to target a broader `against` results in some not great behavior:
```
    …
    # Run breaking change detection against the latest release (in this case v0.1.0)
    - uses: bufbuild/buf-breaking-action@v1
      id: breaking-action
      with:
        against: 'https://github.com/MyOrg/my_repo.git#ref=v0.1.0'
```

Results in the following output:
```
Run bufbuild/buf-breaking-action@v1
  with:
    against: https://github.com/MyOrg/my_repo.git#ref=v0.1.0
    input: .
    buf_input_https_username: zacbir
    buf_input_https_password: ***
Error: Failure: could not clone https://github.com/MyOrg/my_repo.git: exit status 1
error: pathspec 'v0.1.0' did not match any file(s) known to git

Failure: could not clone https://github.com/MyOrg/my_repo.git: exit status 1
error: pathspec 'v0.1.0' did not match any file(s) known to git
```

Given the use of such a marker in the example for testing locally, I had hoped we'd be able to treat releases as the milestones against which we would test for breaking changes. Am I simply spelling it wrong?
