### ISSUE TITLE
Getting error for github action related to writing review commnets

### ISSUE THREAD

**Issue by ashishfw** [bufbuild/buf-breaking-action#76]
Error: Unhandled error: HttpError: Unprocessable Entity: "Pull request review thread path is invalid and Pull request review thread diff hunk can't be blank"

**Comment by ashishfw** [comment]
with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: pullRequest } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number
          });
          const commentBody = "The pull request contains SVG files in the `inline-svg` folder that are too big. Please reduce the size of these files before merging or consider moving those files to another folder.";
          await github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            body: commentBody,
            event: 'COMMENT',
            comments: [{ path: 'frontend/public/assets/inline-svg', position: 1, body: commentBody }],
            commit_id: pullRequest.head.sha
          });
          
          Above script is throwing error

**Comment by nicksnyder** [comment]
It looks like you have written your own script and there is an error somewhere in there. I don't see how this is related to the buf breaking action itself.
