### ISSUE TITLE
Addition of a new proto package is treated as a breaking change

### ISSUE THREAD

**Issue by PrajwalKrishna** [bufbuild/buf-breaking-action#93]
On addition of a new proto package, it sends a failure message like - `Failure: input contained 4 images, whereas against contained 3 images`.

I don't think it should be a breaking change.

**Comment by srikrsna-buf** [comment]
Hey! Could you give us a reproducible example? Are you using workspaces?

**Comment by PrajwalKrishna** [comment]
I found that this issue is because of buf - https://github.com/bufbuild/buf/issues/567
